#!/bin/bash

if [ -d  "./mountdir" ] 
then
    echo "Mount dir Exists !!!!!!!"
else
    echo "Creating ./mountdir folder"
    mkdir mountdir
fi

# to unmount "mountdir" if previously mounted
fusermount -u mountdir 
#ps -x


make
